version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
      docker: 19
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
  pre_build:
    commands:
      - docker --version
      - echo installing libraries and running unit tests...
      - pip install -r requirements.txt
      - python -m pytest tests.py
      - echo logging into ecr...
      - $(aws ecr get-login --no-include-email --region us-west-2)
      - REPOSITORY_URI=INSERT_REPOSITORY_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo building docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo pushing docker image...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
artifacts:
  files:
    - '**/*'
  base_directory: base_location
  name: build-artifacts
  discard-paths: no